apiVersion: v1
kind: Service
metadata:
  name: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps-app
  ports:
    - name: ftp
      protocol: TCP
      port: 21
      targetPort: 21
    - name: ftps-pasv
      protocol: TCP
      port: 20
      targetPort: 20
    - name: ftp-pasv1
      protocol: TCP
      port: 30021
      targetPort: 30021
    - name: ftps-pasv2
      protocol: TCP
      port: 30020
      targetPort: 30020
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps-app
  template:
    metadata:
      labels:
        app: ftps-app
    spec:
      restartPolicy: Always
      containers:
        - image: ftps_alpine:local
          name: ftps-container
          imagePullPolicy: Never
          ports:
            - containerPort: 21
              name: ftp
            - containerPort: 21000
              name: ftps-pasv
          livenessProbe:
            tcpSocket:
              port: 21
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1