apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  type: ClusterIP
  selector:
    app: influxdb-app
  ports:
    - name: influxdb
      protocol: TCP
      port: 8086
      targetPort: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx-deployment
  labels:
    app: influxdb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb-app
  template:
    metadata:
      labels:
        app: influxdb-app
    spec:
      restartPolicy: Always
      containers:
        - name: influxdb-container
          image: influxdb_alpine:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8086
              name: influxdb
          volumeMounts:
            - name: influxdb-volume
              mountPath: /var/lib/influxdb
          livenessProbe:
            tcpSocket:
              port: 8086
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
      volumes:
        - name: influxdb-volume
          persistentVolumeClaim:
            claimName: influxdb-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi