apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  type: LoadBalancer
  selector:
    app: wordpress-app
  ports:
    - name: http
      protocol: TCP
      port: 5050
      targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-app
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      restartPolicy: Always
      containers:
        - name: wordpress-container
          image: wordpress_alpine:local
          imagePullPolicy: Never
          ports:
            - containerPort: 5050
              name: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5050
            initialDelaySeconds: 3
            periodSeconds: 3
            #successThreshold: 1