#!/bin/sh

export TELEGRAF_CONFIG_PATH=/etc/telegraf.conf

nohup sh /root/nohup-mysql.sh > /root/logs 2>&1 &
/usr/bin/mysql_install_db --user=mysql --datadir="/var/lib/mysql"
/usr/bin/mysqld_safe --datadir="/var/lib/mysql" & /usr/bin/telegraf
